version: "3"
services: 
    seleniumhub:
        image: selenium/hub
        ports: 
            - "4446:4444"
    chromenode :
        image: selenium/node-chrome-debug
        ports: 
            - "5901:5900"
        links:
            - seleniumhub:hub
        environment:
            - HUB_PORT_4444_TCP_ADDR=seleniumhub
            - HUB_PORT_4444_TCP_PORT=4444
            - NODE_MAX_INSTANCES=5
            - NODE_MAX_SESSION=5
    firefoxnode :
        image: selenium/node-firefox-debug
        ports: 
            - "5902:5900"
        links:
            - seleniumhub:hub
        environment: 
            - HUB_PORT_4444_TCP_ADDR=seleniumhub
            - HUB_PORT_4444_TCP_PORT=4444
            - NODE_MAX_INSTANCES=5
            - NODE_MAX_SESSION=5

